getclump/clump

- src/main/scala/clump/Clump.scala
- src/test/scala/clump/ClumpApiSpec.scala
@williamboxhall The ```()``` was missing for ```apply```. The consequence is that when using ```clump.apply()```, you are actually using the Clump's ```apply``` and then the Future's ```apply```[1], that is a blocking operation.
[1] https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Future.scala#L655
> fix the apply method

- src/main/scala/clump/Clump.scala
- src/main/scala/clump/ClumpSource.scala
- src/test/scala/clump/ClumpApiSpec.scala
@williamboxhall I think ```orElse``` is more flexible and useful if it receives a clump instead of a value. An actual value it more useful for ```getOrElse```, that is unchanged.
> allow to use a clump for the 'orElse' default value

- src/main/scala/clump/ClumpSource.scala
- src/test/scala/clump/ClumpExecutionSpec.scala
- src/test/scala/clump/ClumpSourceSpec.scala
- src/test/scala/clump/IntegrationSpec.scala
@williamboxhall I find the current ```ClumpSource``` interface confusing. It requires the user to understand the differences between ```list```, ```get```,```getOrElse``` and ```apply```. Considering that the features introduced by the different methods are also provided by the ```Clump``` instances, I think we should remove them.
After the change, the source's interface is really simple, the user needs to use only ```get```.
> simplify the ClumSource's interface

- src/main/scala/clump/Clump.scala
- src/main/scala/clump/ClumpContext.scala
- src/main/scala/clump/ClumpFetcher.scala
- src/main/scala/clump/ClumpSource.scala
@williamboxhall This is more a precaution, I had issues in the past with users extending and overriding the library's classes. We can remove the limitation if necessary in the future.
> don't allow the user extend the Clump's classes

- src/main/scala/clump/Clump.scala
- src/main/scala/clump/ClumpSource.scala
- src/test/scala/clump/ClumpExecutionSpec.scala
- src/test/scala/clump/ClumpFetcherSpec.scala
- src/test/scala/clump/ClumpSourceSpec.scala
- src/test/scala/clump/IntegrationSpec.scala
As discussed in https://github.com/fwbrasil/clump/pull/35, I think it make things nice and simple to have one single entry point for using Clump.
I don't think the interface is too polluted like this
@fwbrasil let's discuss
> Add ClumpSource creation methods to Clump object

- src/test/scala/clump/ClumpSourceSpec.scala
@fwbrasil I don't have time to finish this now as I'm heading out for dinner.
I got all of this compiling for `ClumpSource.apply` however it won't compile for the `ClumpSource.from` eamples
Maybe you can take over if you have time, otherwise I can pick it up next time I have a chance
> Add extra test coverage for flexible sources for different types of iterables in and out

- src/main/scala/clump/Clump.scala
- src/test/scala/clump/ClumpApiSpec.scala
@williamboxhall As ```Future``` does:
https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Future.scala#L943
https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Future.scala#L839
> allow to use partial functions to recover from exceptions

- README.md
Hey man, these are super minor but because it's a very publicly facing document, AND because my mum is an English teacher who has made me very anal, I've made a few very minor typo/grammar fixes.
In particular, "allows to", while being 100% understandable is not technically correct english grammar because "allows" is a transitive verb (so for example you could say "allows ONE to:). So I've fixed the places where I've found that :) make sure you're happy with the changes
> Fix a couple of minor typos and grammar in README

- src/main/scala/clump/Clump.scala
- src/main/scala/clump/ClumpContext.scala
- src/main/scala/clump/ClumpFetcher.scala
- src/main/scala/clump/ClumpSource.scala
I know we had this before @fwbrasil but I would like to bring it back because I think it's really weird that I can manually create a `ClumpMap[Int, Int]` for example, outside of going via the `Clump` companion object. I think it's neater if we just lock these down.
> Make implementations of Clump classes private to clump package so they can't leak

- README.md
- src/main/scala/clump/ClumpContext.scala
- src/main/scala/clump/ClumpSource.scala
- src/main/scala/clump/FunctionIdentity.scala
- src/test/scala/clump/ClumpExecutionSpec.scala
- src/test/scala/clump/ClumpSourceSpec.scala
- src/test/scala/clump/FunctionIdentitySpec.scala
@williamboxhall The current limitation that forces the user to guarantee singleton sources makes harder the adoption of Clump. For instance, it is common to have a parameter with the user's authentication information. 
This pull request removes this limitation and permits the user to use Clump without worrying about the sources being singletons:
```scala
class TrackRepository(users: UserRepository) {
private def trackSourceFor(session: Session) = Clump.source(tracksService.fetch(session, _))(_.trackId)
def trackClump(session: Session, trackId: Long): Clump[Track] =
for {
track <- trackSourceFor(session).get(trackId)
user <- users.userClump(session, track.userId)
} yield {
new EnrichedTrack(track, user)
}
}
```
The ```FunctionIdentity``` class is capable to detect if the function has the …
> permit the usage of non-singleton sources

- src/main/scala/clump/Clump.scala
- src/test/scala/clump/ClumpApiSpec.scala
@williamboxhall I find ```Clump.None``` confusing, since it is different from ```Future.None```.
```scala
val clump: Clump[Track] = Clump.None
val future: Future[Option[Tack]] = Future.None
```
I think ```Clump.empty``` is a better name.
> rename Clump.None to Clump.empty

- src/main/scala/clump/Clump.scala
- src/test/scala/clump/ClumpApiSpec.scala
@williamboxhall Another small change. The for-comprehension fallbacks to ```filter``` if ```withFilter``` is not present. I think ```filter``` is more user-friendly.
See the "About withFilter, and strictness" section here:
http://docs.scala-lang.org/tutorials/FAQ/yield.html
> rename 'withFilter' to 'filter'

- src/main/scala/clump/Clump.scala
@williamboxhall The compiler is generating this warning:
```
withFilter' method does not yet exist on clump.Clump[representation.Track], using filter' method instead
```
> add the 'withFilter' method again

- src/main/scala/clump/Clump.scala
- src/test/scala/clump/ClumpApiSpec.scala
@williamboxhall I know that it is ugly, but scala doesn't support "tuple flattening". The Twitter Future also has these methods:
https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Future.scala#L198
> add methods to join multiple clump instances

- src/main/scala/io/getclump/Clump.scala
- src/main/scala/io/getclump/ClumpSource.scala
- src/test/scala/io/getclump/ClumpSourceSpec.scala
@williamboxhall @grandbora Scrooge generates classes for the thrift IDLs that use `scala.collection.Map` instead of `scala.collection.immutable.Map`, so it isn't possible to use them directly. This PR changes the `Clump.sourceFrom` to accept `Iterable[(Key,Value)]`, that includes both.
> support iterable outputs (Clump.sourceFrom)

- README.md
- src/main/scala/io/getclump/Clump.scala
- src/test/scala/io/getclump/ClumpApiSpec.scala
@philwills @williamboxhall It is possible to overload because the `ClassTag` generates an implicit parameter that is provided automatically by the compiler, so the signature isn't the same and we can workaround the type erasure.
> overload `Clump.future` to accept both `Future[T]` and `Future[Option[T]]`

- README.md
- src/main/scala/io/getclump/Clump.scala
- src/main/scala/io/getclump/ClumpSource.scala
- src/main/scala/io/getclump/FutureBridge.scala
- src/main/scala/io/getclump/Joins.scala
- src/main/scala/io/getclump/Sources.scala
Some of these methods are already better explained in the README but this provides a starting point for documenting the project.
> Add scaladoc to all public methods

- src/main/scala/io/getclump/Clump.scala
- src/main/scala/io/getclump/ClumpSource.scala
- src/test/scala/io/getclump/ClumpApiSpec.scala
The most useful of these to me is `default`. I want to be able to go:
```scala
for {
list <- clumpSourceThatReturnsList.get(id).default(Nil)
} yield {
// code
}
```
instead of having to do this all the time:
```scala
for {
listOption <- clumpSourceThatReturnsList.get(id).optional
} yield {
val list = listOption.getOrElse(Nil)
// code
}
```
> Add a couple inferred methods and aliases to clump api

- src/main/scala/io/getclump/ClumpFetcher.scala
- src/main/scala/io/getclump/ClumpSource.scala
- src/main/scala/io/getclump/Sources.scala
- src/test/scala/io/getclump/ClumpFetcherSpec.scala
> Change ClumpSource/Fetcher to honour call order

- src/main/scala/io/getclump/ClumpSource.scala
- src/test/scala/io/getclump/ClumpSourceSpec.scala
@williamboxhall @stevenheidel 
I spent many days trying to identify the cause for a production issue and in the end the main problem was the size of the batch requests to memcached. The system was making requests for batches with thousands of keys.
We need to avoid letting users run into similar problems. This pull request sets the default `maxBatchSize` to `100`. Another alternative would be make the `maxBatchSize` required when creating a `ClumpSource`.
> limit the default max batch size

- README.md
- STITCH.md
- src/main/scala/io/getclump/ClumpContext.scala
- src/main/scala/io/getclump/package-twitter.scala.tmpl
- src/test/scala/io/getclump/ClumpExecutionSpec.scala
Motivating example from our code:
```scala
Clump.join(
profiles.get(123).optional,
companies.get(456)
)
```
You'd expect this to make a call to `profiles` and `companies` at the same time. However, because they are at different levels the current algorithm waits until after `profiles` is done before getting `companies`.
This changes the flush method to walk to the bottom of the entire upstream path and do all the fetches at once, then walk back up the downstreams one by one resolving them in order. This means `profiles` and `companies` will now be executed in parallel as expected, and doing any number of simple .maps or .optionals on a fetch will not affect its parallelism. This also means Clumps joined 3 ways will happen in parallel as well, which I don't believe was the case before …
> Optimize ClumpContext execution algorithm to fetch in parallel at diferent levels of composition

- src/main/scala/io/getclump/Clump.scala
Confession to start: I don't have a clear 100% understanding of CanBuildFrom. We experienced an issue in our codebase where we have a very specialized collection type that contains some metadata associated with it. This metadata was being lost by Clump. The solution was just to add a seed to the apply() method of cbf which seems to copy over everything but the elements from the original collection.
> Fix issue with CanBuildFrom and collections with metadata

- README.md
- src/main/scala/io/getclump/Clump.scala
- src/test/scala/io/getclump/ClumpApiSpec.scala
- src/test/scala/io/getclump/ClumpExecutionSpec.scala
**Motivation**: Clump in general does a very good job of hiding its implementation details. For example, it's not required to know about `ClumpFlatMap`, `ClumpOrElse`, etc. to use the API. However, I feel like there's one place where this abstraction leaks: namely that values not returned by sources are internally stored as an `Option`.
This presents a major problem when working with `Clump[Option[T]]` because several APIs are overloaded and take `Option` to mean the underlying implementation `Option` and not the user facing `Option`.
Here's some examples of real problems we've had with this:
1: It leads to surprising types.
```scala
Clump.value(2): Clump[Int] // a value
Clump.value(List(2)): Clump[List[Int]] // a value with a context
Clump.value(Some(2)): Clump[Int] // a value again??? …
```
> Simplify API to no longer expose internal Option

- src/main/scala/io/getclump/ClumpContext.scala
- src/main/scala/io/getclump/ClumpFetcher.scala
- src/test/scala/io/getclump/ClumpExecutionSpec.scala
A coworker found an edge case that meant we weren't optimally batching in the flushDownstream method. I had to make the `getClumpsByLevel` a bit more sophisticated to handle this.
> Fix batching for nested flatmaps at different levels of composition

- README.md
- src/main/scala/io/getclump/Clump.scala
- src/main/scala/io/getclump/ClumpSource.scala
In case anyone is browsing through a system and looks up a Clump, we want to have a good explanation of what it is in that file. Similar to the documentation above Future.
> Add docs to Clump and ClumpSource files
