getclump/clump

- src/main/scala/clump/Clump.scala
- src/main/scala/clump/ClumpSource.scala
- src/test/scala/clump/ClumpApiSpec.scala
- src/test/scala/clump/ClumpExecutionSpec.scala
- src/test/scala/clump/ClumpFetcherSpec.scala
- src/test/scala/clump/ClumpSourceSpec.scala
- src/test/scala/clump/IntegrationSpec.scala
> Flexible sources

- src/main/scala/clump/ClumpSource.scala
- src/test/scala/clump/ClumpSourceSpec.scala
- src/test/scala/clump/IntegrationSpec.scala
@fwbrasil as discussed in https://github.com/fwbrasil/clump/pull/35
Please merge if you like
> Minor style changes for ClumpSource and its usage

- .travis.yml
@williamboxhall To reduce the noise.
> disable travis-ci notifications

- STITCH.md
@williamboxhall This is the initial draft. Do you remember other main diferences?
> Documentation comparing Clump and Stitch

- README.md
- src/main/scala/clump/FutureBridge.scala
- src/test/scala/clump/FutureBridgeSpec.scala
@williamboxhall This will help users that use the scala futures.
> allow to use scala futures

- src/main/scala/clump/Clump.scala
- src/main/scala/clump/ClumpFetcher.scala
- src/main/scala/clump/ClumpSource.scala
- src/test/scala/clump/ClumpFetcherSpec.scala
This doesn't even compile and it's very ugly but I ran out of time to keep working on it today so I thought I'd throw it to you for comment/to keep working on it if you want to.
You should be able to get the idea based off the new method I've added to ClumpSource.
@fwbrasil let me know what you think?
> built-in retries for failed fetches

- README.md
@williamboxhall 
See #54 
There is also a commit to remove unnecessary indentation of some code examples.
> documentation for 'maxRetries'

- README.md
- src/main/scala/clump/ClumpFetcher.scala
- src/test/scala/clump/ClumpFetcherSpec.scala
> remove the per-key retry feature

- .travis.yml
- build.sbt
- project/plugins.sbt
- version.sbt
> cross compile scala 2.11

- README.md
@williamboxhall I spoke with some people today about Clump and the first thing they ask for is an example of code before and after using the library.
> readme - add example of the same composition with and without clump

- README.md
- src/main/scala/clump/Clump.scala
- src/test/scala/clump/ClumpSourceSpec.scala
@williamboxhall Helping the scala's compiler type inference. :(
> better support for expanded functions

- README.md
- src/main/scala/io/getclump/Clump.scala
- src/test/scala/io/getclump/ClumpApiSpec.scala
> accept any kind of collection for clump.collect and clump.flatten

- README.md
> add note about the known limitation and the implicit cache

- README.md
ONE FOR THE TEAM!
@fwbrasil @williamboxhall  please review.
> add missing square bracket

- README.md
> Fixed import in README example

- src/main/scala/io/getclump/Clump.scala
- src/test/scala/io/getclump/ClumpApiSpec.scala
- src/test/scala/io/getclump/IntegrationSpec.scala
> Implement generic Clump.traverse

- STITCH.md
> update the stitch doc

- src/main/scala/io/getclump/ClumpSource.scala
- src/test/scala/io/getclump/ClumpSourceSpec.scala
> Support generic collection type for ClumpSource get multiple

- src/main/scala/io/getclump/Sources.scala
- src/main/scala/io/getclump/Tuples.scala
- src/test/scala/io/getclump/IntegrationSpec.scala
- src/test/scala/io/getclump/SourcesSpec.scala
Currently intellij gets sad and can't handle the higher kinded type inference when you do this
@fwbrasil
> Support for sourcing singly keyed fetch functions

- .travis.yml
- README.md
- build.sh
- project/Build.scala
- project/build.properties
- project/plugins.sbt
Codacy isn't reliable for code coverage reports. I've seen it report more than 100% coverage more than once.
cc/ @williamboxhall @stevenheidel
> use codecov.io for code coverage
